import { Provider } from "./types";

export const providers: Provider[] = [
  {
    id: "sg-reg-1",
    name: "LionBridge Corporate",
    country: "新加坡",
    city: "Singapore",
    serviceTypes: ["公司注册", "税务"],
    priceRange: "SGD 1,500 - 3,500",
    timeline: "5-10 个工作日",
    languages: ["中文", "英文"],
    rating: 4.8,
    reviewCount: 126,
    trustTags: ["已认证", "平台担保"],
    credentials: ["ACRA Filing Agent", "税务代理资质"],
    description: "擅长中国团队新加坡公司落地与税务合规。",
    cases: ["跨境电商 Pte. Ltd. 设立", "SaaS 公司税务架构"],
    keywords: ["新加坡", "公司注册", "Pte", "税务", "合规"],
  },
  {
    id: "sg-visa-1",
    name: "Merlion Visa Partners",
    country: "新加坡",
    city: "Singapore",
    serviceTypes: ["签证"],
    priceRange: "SGD 900 - 2,200",
    timeline: "2-4 周",
    languages: ["中文", "英文"],
    rating: 4.6,
    reviewCount: 88,
    trustTags: ["已认证"],
    credentials: ["持牌移民顾问"],
    description: "就业准证、家属准证和创业准证办理经验丰富。",
    cases: ["EP 申请加急", "创业准证材料辅导"],
    keywords: ["新加坡", "签证", "EP", "创业准证"],
  },
  {
    id: "sg-tm-1",
    name: "Straits IP Studio",
    country: "新加坡",
    city: "Singapore",
    serviceTypes: ["商标"],
    priceRange: "SGD 700 - 1,800",
    timeline: "1-3 个月",
    languages: ["中文", "英文"],
    rating: 4.7,
    reviewCount: 64,
    trustTags: ["已认证", "案例已验证"],
    credentials: ["IPOS 代理合作"],
    description: "东南亚商标布局与异议应对。",
    cases: ["跨境品牌新加坡商标申请"],
    keywords: ["新加坡", "商标", "IPOS", "品牌"],
  },
  {
    id: "uk-reg-1",
    name: "Thames Company Hub",
    country: "英国",
    city: "London",
    serviceTypes: ["公司注册", "税务"],
    priceRange: "GBP 300 - 1,200",
    timeline: "3-7 个工作日",
    languages: ["中文", "英文"],
    rating: 4.5,
    reviewCount: 95,
    trustTags: ["已认证"],
    credentials: ["Companies House 代理", "HMRC 税务顾问"],
    description: "英国公司设立、VAT 注册与年度申报。",
    cases: ["留学生创业 Ltd 注册"],
    keywords: ["英国", "公司注册", "Ltd", "VAT", "税务"],
  },
  {
    id: "uk-visa-1",
    name: "BritPath Immigration",
    country: "英国",
    city: "Manchester",
    serviceTypes: ["签证"],
    priceRange: "GBP 1,200 - 3,000",
    timeline: "3-8 周",
    languages: ["中文", "英文"],
    rating: 4.4,
    reviewCount: 73,
    trustTags: ["已认证", "平台担保"],
    credentials: ["OISC 注册"],
    description: "工签、创业签与续签方案咨询。",
    cases: ["工签续签", "毕业签转工签"],
    keywords: ["英国", "签证", "工签", "续签"],
  },
  {
    id: "uk-tm-1",
    name: "Crown Trademark Counsel",
    country: "英国",
    city: "London",
    serviceTypes: ["商标"],
    priceRange: "GBP 500 - 1,500",
    timeline: "2-4 个月",
    languages: ["中文", "英文"],
    rating: 4.6,
    reviewCount: 58,
    trustTags: ["已认证"],
    credentials: ["UKIPO 代理"],
    description: "UK/EU 商标申请与驳回复审。",
    cases: ["跨境电商品牌 UKIPO 注册"],
    keywords: ["英国", "商标", "UKIPO", "品牌"],
  },
  {
    id: "ca-reg-1",
    name: "Maple Startup Desk",
    country: "加拿大",
    city: "Toronto",
    serviceTypes: ["公司注册", "税务"],
    priceRange: "CAD 600 - 2,000",
    timeline: "1-2 周",
    languages: ["中文", "英文"],
    rating: 4.7,
    reviewCount: 81,
    trustTags: ["已认证", "案例已验证"],
    credentials: ["CRA 合作顾问"],
    description: "联邦/省级注册与税务申报全流程。",
    cases: ["安省公司注册", "GST/HST 报税"],
    keywords: ["加拿大", "公司注册", "税务", "GST", "HST"],
  },
  {
    id: "ca-visa-1",
    name: "NorthGate Mobility",
    country: "加拿大",
    city: "Vancouver",
    serviceTypes: ["签证"],
    priceRange: "CAD 1,000 - 2,800",
    timeline: "4-10 周",
    languages: ["中文", "英文"],
    rating: 4.5,
    reviewCount: 69,
    trustTags: ["已认证"],
    credentials: ["RCIC 持牌顾问"],
    description: "工签、学签、家属签证与续签支持。",
    cases: ["工签延期", "学签转工签"],
    keywords: ["加拿大", "签证", "工签", "学签"],
  },
  {
    id: "ca-tm-1",
    name: "Aurora IP Works",
    country: "加拿大",
    city: "Montreal",
    serviceTypes: ["商标"],
    priceRange: "CAD 700 - 1,900",
    timeline: "3-6 个月",
    languages: ["中文", "英文", "法文"],
    rating: 4.6,
    reviewCount: 52,
    trustTags: ["已认证"],
    credentials: ["CIPO 代理"],
    description: "加拿大商标申请与跨境品牌保护。",
    cases: ["消费品牌 CIPO 申请"],
    keywords: ["加拿大", "商标", "CIPO", "品牌"],
  },
  {
    id: "us-reg-1",
    name: "Liberty Launch Advisors",
    country: "美国",
    city: "Delaware",
    serviceTypes: ["公司注册", "税务"],
    priceRange: "USD 500 - 2,500",
    timeline: "3-8 个工作日",
    languages: ["中文", "英文"],
    rating: 4.8,
    reviewCount: 142,
    trustTags: ["已认证", "平台担保", "案例已验证"],
    credentials: ["州注册代理", "CPA 团队"],
    description: "美国 LLC/C-Corp 设立与税务合规。",
    cases: ["Delaware C-Corp 设立", "EIN 快速申请"],
    keywords: ["美国", "公司注册", "LLC", "C-Corp", "税务"],
  },
  {
    id: "us-visa-1",
    name: "Eagle Visa Counsel",
    country: "美国",
    city: "San Francisco",
    serviceTypes: ["签证"],
    priceRange: "USD 1,500 - 5,000",
    timeline: "4-12 周",
    languages: ["中文", "英文"],
    rating: 4.4,
    reviewCount: 77,
    trustTags: ["已认证"],
    credentials: ["美国移民律师合作"],
    description: "工作签证与创业者签证路线规划。",
    cases: ["H-1B 材料准备", "L1 架构咨询"],
    keywords: ["美国", "签证", "H1B", "L1", "移民"],
  },
  {
    id: "us-tm-1",
    name: "Pacific Trademark Lab",
    country: "美国",
    city: "Los Angeles",
    serviceTypes: ["商标"],
    priceRange: "USD 600 - 2,200",
    timeline: "2-6 个月",
    languages: ["中文", "英文"],
    rating: 4.5,
    reviewCount: 61,
    trustTags: ["已认证"],
    credentials: ["USPTO 代理"],
    description: "美国商标申请、驳回答复与监测。",
    cases: ["跨境品牌 USPTO 注册"],
    keywords: ["美国", "商标", "USPTO", "品牌"],
  },
  {
    id: "sg-tax-2",
    name: "Bayfront Tax Partners",
    country: "新加坡",
    city: "Singapore",
    serviceTypes: ["税务"],
    priceRange: "SGD 1,000 - 2,800",
    timeline: "1-2 周",
    languages: ["中文", "英文"],
    rating: 4.3,
    reviewCount: 45,
    trustTags: ["已认证"],
    credentials: ["IRAS 税务顾问"],
    description: "企业所得税、GST 与账务申报服务。",
    cases: ["初创企业年报与税务整备"],
    keywords: ["新加坡", "税务", "IRAS", "GST"],
  },
  {
    id: "uk-tax-2",
    name: "Albion Tax Studio",
    country: "英国",
    city: "Birmingham",
    serviceTypes: ["税务"],
    priceRange: "GBP 450 - 1,600",
    timeline: "1-3 周",
    languages: ["中文", "英文"],
    rating: 4.2,
    reviewCount: 39,
    trustTags: ["已认证"],
    credentials: ["ACCA 团队"],
    description: "VAT、Payroll、企业税务合规支持。",
    cases: ["跨境团队薪税合规"],
    keywords: ["英国", "税务", "VAT", "Payroll"],
  },
  {
    id: "ca-tax-2",
    name: "TrueNorth Finance",
    country: "加拿大",
    city: "Calgary",
    serviceTypes: ["税务"],
    priceRange: "CAD 500 - 1,700",
    timeline: "1-3 周",
    languages: ["中文", "英文"],
    rating: 4.4,
    reviewCount: 41,
    trustTags: ["已认证"],
    credentials: ["CPA Canada"],
    description: "企业税务申报与跨省税务规划。",
    cases: ["小型企业税务优化"],
    keywords: ["加拿大", "税务", "CPA"],
  },
];
